<a href="https://colab.research.google.com/github/Aman12457/Upgradation/blob/main/Flight_Price_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [97]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_excel('flight_price.xlsx')

In [98]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [99]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

In [100]:
df.describe()

              Price
count  10683.000000
mean    9087.064121
std     4611.359167
min     1759.000000
25%     5277.000000
50%     8372.000000
75%    12373.000000
max    79512.000000

In [101]:
df['Airline'].value_counts()

Airline
Jet Airways                          3849
IndiGo                               2053
Air India                            1752
Multiple carriers                    1196
SpiceJet                              818
Vistara                               479
Air Asia                              319
GoAir                                 194
Multiple carriers Premium economy      13
Jet Airways Business                    6
Vistara Premium economy                 3
Trujet                                  1
Name: count, dtype: int64

In [102]:
## Feature Enginering
## let's start with the date of journey
df['Date'] = df['Date_of_Journey'].str.split('/').str[0]
df['Month'] = df['Date_of_Journey'].str.split('/').str[1]
df['Year'] = df['Date_of_Journey'].str.split('/').str[2]

In [103]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,03,2019
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,05,2019
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,06,2019
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,05,2019
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,01,03,2019

In [104]:
df['Date'] = df['Date'].astype(int)
df['Month'] = df['Month'].astype(int)
df['Year'] = df['Year'].astype(int)

In [105]:
## drop 'date of journey' col
df.drop('Date_of_Journey',axis=1 , inplace=True)

In [106]:
df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,6,2019
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,5,2019
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1,3,2019

In [107]:
df['arrival_hour'] = df['Arrival_Time'].str.split(':').str[0]

In [108]:
df['arrival_min'] = df['Arrival_Time'].str.split(':').str[1].str.split(' ').str[0]

In [109]:
df['arrival_hour'] = df['arrival_hour'].astype(int)
df['arrival_min'] = df['arrival_min'].astype(int)

In [110]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Source           10683 non-null  object
 2   Destination      10683 non-null  object
 3   Route            10682 non-null  object
 4   Dep_Time         10683 non-null  object
 5   Arrival_Time     10683 non-null  object
 6   Duration         10683 non-null  object
 7   Total_Stops      10682 non-null  object
 8   Additional_Info  10683 non-null  object
 9   Price            10683 non-null  int64
 10  Date             10683 non-null  int64
 11  Month            10683 non-null  int64
 12  Year             10683 non-null  int64
 13  arrival_hour     10683 non-null  int64
 14  arrival_min      10683 non-null  int64
dtypes: int64(6), object(9)
memory usage: 1.2+ MB

In [111]:
df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,arrival_hour,arrival_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019,1,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019,13,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,6,2019,4,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,5,2019,23,30
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1,3,2019,21,35

In [112]:
df.drop('Arrival_Time' , axis=1 , inplace=True)

In [113]:
df.head()

,Airline,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,arrival_hour,arrival_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,2h 50m,non-stop,No info,3897,24,3,2019,1,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,7h 25m,2 stops,No info,7662,1,5,2019,13,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,19h,2 stops,No info,13882,9,6,2019,4,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,5h 25m,1 stop,No info,6218,12,5,2019,23,30
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,4h 45m,1 stop,No info,13302,1,3,2019,21,35

In [114]:
## converting departure time into dept_hour and dept_min
df['dept_hour'] = df['Dep_Time'].str.split(':').str[0]
df['dept_min'] = df['Dep_Time'].str.split(':').str[1]

In [115]:
df['dept_hour'] = df['dept_hour'].astype(int)
df['dept_min'] = df['dept_min'].astype(int)

In [116]:
df.drop('Dep_Time' , axis=1 , inplace=True)

In [117]:
df.head(2)

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,arrival_hour,arrival_min,dept_hour,dept_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,3897,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2 stops,No info,7662,1,5,2019,13,15,5,50

In [118]:
## Total_Stops turn
df['Total_Stops'].unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops'],
      dtype=object)

In [119]:
df['Total_Stops'].isnull().sum()

np.int64(1)

In [120]:
df['Total_Stops'] = df['Total_Stops'].map({'non-stop':0,'1 stop':1,'2 stops':2,'3 stops':3,'4 stops':4,np.nan:1})

In [121]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Source           10683 non-null  object
 2   Destination      10683 non-null  object
 3   Route            10682 non-null  object
 4   Duration         10683 non-null  object
 5   Total_Stops      10683 non-null  int64
 6   Additional_Info  10683 non-null  object
 7   Price            10683 non-null  int64
 8   Date             10683 non-null  int64
 9   Month            10683 non-null  int64
 10  Year             10683 non-null  int64
 11  arrival_hour     10683 non-null  int64
 12  arrival_min      10683 non-null  int64
 13  dept_hour        10683 non-null  int64
 14  dept_min         10683 non-null  int64
dtypes: int64(9), object(6)
memory usage: 1.2+ MB

In [122]:
df[df['Total_Stops'].isnull()]

Empty DataFrame
Columns: [Airline, Source, Destination, Route, Duration, Total_Stops, Additional_Info, Price, Date, Month, Year, arrival_hour, arrival_min, dept_hour, dept_min]
Index: []

In [124]:
df['Total_Stops'].value_counts()

Total_Stops
1    5626
0    3491
2    1520
3      45
4       1
Name: count, dtype: int64

In [125]:
df.head(2)

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,arrival_hour,arrival_min,dept_hour,dept_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,0,No info,3897,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2,No info,7662,1,5,2019,13,15,5,50

In [126]:
## no need for route here
df.drop('Route' , axis=1 , inplace=True)

In [127]:
df.head(1)

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,arrival_hour,arrival_min,dept_hour,dept_min
0,IndiGo,Banglore,New Delhi,2h 50m,0,No info,3897,24,3,2019,1,10,22,20

In [139]:
## conversion of duration
df['duration_hour'] = pd.to_numeric(df['Duration'].str.split(' ').str[0].str.split('h').str[0] , errors= 'coerce')
df['duration_min'] = pd.to_numeric(df['Duration'].str.split(' ').str[1].str.split('m').str[0] , errors = 'coerce')

In [140]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Source           10683 non-null  object
 2   Destination      10683 non-null  object
 3   Duration         10683 non-null  object
 4   Total_Stops      10683 non-null  int64
 5   Additional_Info  10683 non-null  object
 6   Price            10683 non-null  int64
 7   Date             10683 non-null  int64
 8   Month            10683 non-null  int64
 9   Year             10683 non-null  int64
 10  arrival_hour     10683 non-null  int64
 11  arrival_min      10683 non-null  int64
 12  dept_hour        10683 non-null  int64
 13  dept_min         10683 non-null  int64
 14  duration_hour    10682 non-null  float64
 15  duration_min     9651 non-null   float64
dtypes: float64(2), int64(9), object(5)
memory usage: 1.3+ MB

In [141]:
df['duration_min'].unique()

array([50., 25., nan, 45., 30.,  5., 15., 35., 10., 20., 55., 40.])

In [143]:
df['Duration'].isnull().sum()

np.int64(0)

In [144]:
df['duration_hour'].fillna(0 , inplace=True)
df['duration_min'].fillna(0 , inplace=True)

/tmp/ipython-input-3685248750.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['duration_hour'].fillna(0 , inplace=True)
/tmp/ipython-input-3685248750.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['duration_min'].fillna(0 , inplace=True)

In [145]:
df['duration_hour'].isnull().sum()

np.int64(0)

In [147]:
df.drop('Duration' , axis=1 , inplace= True)

In [148]:
df.head(1)

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Date,Month,Year,arrival_hour,arrival_min,dept_hour,dept_min,duration_hour,duration_min
0,IndiGo,Banglore,New Delhi,0,No info,3897,24,3,2019,1,10,22,20,2.0,50.0

In [149]:
## converting additional info into numerical feature vector
df['Additional_Info'].unique()

array(['No info', 'In-flight meal not included',
       'No check-in baggage included', '1 Short layover', 'No Info',
       '1 Long layover', 'Change airports', 'Business class',
       'Red-eye flight', '2 Long layover'], dtype=object)

In [150]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
## feed the above values to the encoder
ohe.fit_transform(df[['Source','Destination','Airline']]).toarray()

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 0., 0.]])

In [151]:
encoded_df = pd.DataFrame(ohe.fit_transform(df[['Source','Destination','Airline']]).toarray() , columns=ohe.get_feature_names_out())

In [154]:
final_df = pd.concat([encoded_df , df] , axis =1)

In [155]:
final_df.head(2)

,Source_Banglore,Source_Chennai,Source_Delhi,Source_Kolkata,Source_Mumbai,Destination_Banglore,Destination_Cochin,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,...,Price,Date,Month,Year,arrival_hour,arrival_min,dept_hour,dept_min,duration_hour,duration_min
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3897,24,3,2019,1,10,22,20,2.0,50.0
1,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,7662,1,5,2019,13,15,5,50,7.0,25.0

In [162]:
final_df.drop(['Source','Destination','Airline'] , axis=1 , inplace=True)

In [161]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 38 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Source_Banglore                            10683 non-null  float64
 1   Source_Chennai                             10683 non-null  float64
 2   Source_Delhi                               10683 non-null  float64
 3   Source_Kolkata                             10683 non-null  float64
 4   Source_Mumbai                              10683 non-null  float64
 5   Destination_Banglore                       10683 non-null  float64
 6   Destination_Cochin                         10683 non-null  float64
 7   Destination_Delhi                          10683 non-null  float64
 8   Destination_Hyderabad                      10683 non-null  float64
 9   Destination_Kolkata                        10683 non-null  float64
 10  Destination_New Delhi                      10683 non-null  float64
 11  Airline_Air Asia                           10683 non-null  float64
 12  Airline_Air India                          10683 non-null  float64
 13  Airline_GoAir                              10683 non-null  float64
 14  Airline_IndiGo                             10683 non-null  float64
 15  Airline_Jet Airways                        10683 non-null  float64
 16  Airline_Jet Airways Business               10683 non-null  float64
 17  Airline_Multiple carriers                  10683 non-null  float64
 18  Airline_Multiple carriers Premium economy  10683 non-null  float64
 19  Airline_SpiceJet                           10683 non-null  float64
 20  Airline_Trujet                             10683 non-null  float64
 21  Airline_Vistara                            10683 non-null  float64
 22  Airline_Vistara Premium economy            10683 non-null  float64
 23  Airline                                    10683 non-null  object
 24  Source                                     10683 non-null  object
 25  Destination                                10683 non-null  object
 26  Total_Stops                                10683 non-null  int64
 27  Additional_Info                            10683 non-null  object
 28  Price                                      10683 non-null  int64
 29  Date                                       10683 non-null  int64
 30  Month                                      10683 non-null  int64
 31  Year                                       10683 non-null  int64
 32  arrival_hour                               10683 non-null  int64
 33  arrival_min                                10683 non-null  int64
 34  dept_hour                                  10683 non-null  int64
 35  dept_min                                   10683 non-null  int64
 36  duration_hour                              10683 non-null  float64
 37  duration_min                               10683 non-null  float64
dtypes: float64(25), int64(9), object(4)
memory usage: 3.1+ MB

In [163]:
final_df.drop('Additional_Info', axis=1 , inplace=True)

In [164]:
final_df.head(2)

,Source_Banglore,Source_Chennai,Source_Delhi,Source_Kolkata,Source_Mumbai,Destination_Banglore,Destination_Cochin,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,...,Price,Date,Month,Year,arrival_hour,arrival_min,dept_hour,dept_min,duration_hour,duration_min
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3897,24,3,2019,1,10,22,20,2.0,50.0
1,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,7662,1,5,2019,13,15,5,50,7.0,25.0

In [166]:
final_df.shape

(10683, 34)